#!/bin/env python
import signal
from pyspin_camera import video_sender
import sys

if __name__ == "__main__":
    signal.signal(signal.SIGINT, signal.SIG_DFL)

    q = video_sender.QApplication(sys.argv)
    q.exec_()

if __name__ == "__main__":
    main()
